### ISSUE TITLE
3.6版本更新后无法正常使用

### ISSUE THREAD

**Issue by GreenGhost1** [iyzyi/Genshin-Auto-Skip-Cutscenes#5]
出现选项时可以点击，但是对话过程不能自动点击

**Comment by iyzyi** [comment]
感谢反馈，目前已修复。
可从[Releases](https://github.com/iyzyi/Genshin-Auto-Skip-Cutscenes/releases/)页面重新下载v1.1。
出现问题的原因是新版本米哈游更改了自动播放剧情那个按钮的坐标以及透明度。

**Comment by iyzyi** [comment]
感谢反馈，目前已修复。
可从[Releases](https://github.com/iyzyi/Genshin-Auto-Skip-Cutscenes/releases/)页面重新下载v1.1。
出现问题的原因是新版本米哈游更改了自动播放剧情那个按钮的坐标以及透明度。
