### ISSUE TITLE
3.6后就不能正常使用，只能点有对话选项的

### ISSUE THREAD

**Issue by xiaoxiaoxiaoying** [iyzyi/Genshin-Auto-Skip-Cutscenes#6]

**Comment by iyzyi** [comment]
感谢反馈，目前已修复。
可从[Releases](https://github.com/iyzyi/Genshin-Auto-Skip-Cutscenes/releases/)页面重新下载v1.1。
出现问题的原因是新版本米哈游更改了自动播放剧情那个按钮的坐标以及透明度。

**Comment by xiaoxiaoxiaoying** [comment]
感谢大佬！❤
